### PR TITLE
added leaderless bft consensus

### PR DESCRIPTION
**Pull request by gitferry**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] If you own an Economic Node or Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to bounty@vechain.com to claim the additional grant.

### CODE REVIEW

**Review by playboybkc — DISMISSED** [review]

**Comment by Zhijieren** [comment]
Please add following items in order to proceed to the next step of the reviewing process.

- A corresponding applicant for this proposal (the role of a corresponding applicant is described in the up-to-date version of the template.
- It appears that the document provided as the plan is modified from a pre-print paper. It is unclear how the result of the paper is related to this project, e.g., is the project a follow-up study of the paper, or implementation of the paper, or is the described scheme is not yet complete. We expect the applicants to clarify the exact purpose of this project before we proceed to the committee reviewing phase.

**Comment by gitferry** [comment]
Many thanks to @Zhijieren for the comment. I have made changes accordingly. Please review it again. Thanks!

**Comment by Zhijieren** [comment]
@gitferry 
Please note that milestones should be tangible and verifiable (note that the grant is disbursed based on the milestones). Hence, it should be clarified that in which form the milestone 2 and 3 will be delivered.

**Comment by gitferry** [comment]
@Zhijieren 
Detailed output for each milestone is updated. Thanks!

**Comment by gitferry** [comment]
@Zhijieren 
Budget details are updated.

**Comment by jahlearn** [comment]
can anyone teach me

**Review by Zhijieren — APPROVED** [review]

**Review by zzGHzz — APPROVED** [review]

**Comment by NecoSherry** [comment]
@gitferry  Congratulations! Your application has been accepted! We need to contact you on email for the payment of the first milestone. We'll take the following steps: 

Step1. Please email grant@vechain.org with your project name, pr link, Ethereum Address(same with the address in your application). 

Step2. Once the fund is disbursed, we will email you the TxID to let you know.

Step3. Please reply a receipt to confirm that you have received the fund.

**Comment by gitferry** [comment]
@NecoSherry Many thanks! One quick question, is the grant sent by Ether or USDT (ERC 20)? It would be great if I can receive the grant by Ether, but it might not be the same address in my application.

**Pull request merged**
