### PR TITLE
Sozo inFashion Milestone 1 Delivery

### PR DESCRIPTION
**Pull request by Zibilicious**
# Grant Application Checklist

- [ ] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] An Ethereum address for the payment of the milestones is provided inside the application.  
- [ ] The total funding amount of the project is up to USD $30k for every grant applications.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Review by libotony — APPROVED** [review]

**Review by NecoSherry — APPROVED** [review]

**Comment by NecoSherry** [comment]
Thank you for delivering milestone 1. We will promptly proceed with the payment process for milestones 2. Before we make the payment, could you please confirm if the payment address is still the same as in your application?

**Comment by Zibilicious** [comment]
Yes, the payment address has not changed and is the same. Thank you.

**Comment by Zibilicious** [comment]
Hi @NecoSherry, just wanted to check in on the status of this? Thank you!

**Comment by Zibilicious** [comment]
Hi @NecoSherry, we still have not seen the payment go through on the wallet
address, can you confirm when we can expect it?

Thank you!
Zi

**Comment by NecoSherry** [comment]
@Zibilicious We understand the urgency and are working to process the payment as quickly as possible. We appreciate your patience and will notify you as soon as the payment has been completed.

**Comment by Zibilicious** [comment]
Thank you for your response!

**Pull request merged**
