### PR TITLE
Create vesea_nft_platform.md

### PR DESCRIPTION
**Pull request by Bread-VeSea**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [X] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] If you own an Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to grant@vechain.org to claim the additional grant.

### CODE REVIEW

**Comment by NecoSherry** [comment]
@Bread-VeSea  Thanks for the application. 

Could you update the milestone deliverables? See https://github.com/vechain/grant-program/blob/master/applications/application-template.md. Deliverables 0a-0c are mandatory for all milestones. If you do not intend to deliver one of these, please state a reason in its specification (e.g. Milestone X is research oriented and as such there is no code to test).

For the testing guide, core functions will be fully covered by unit tests to ensure functionality and robustness. In the guide, you will describe how to run these tests.

For the documentation, it’s better to provide inline documentation and a basic tutorial that can interact with the deployed smart contracts and backend service. Whenever milestones are delivered, we refer to this document to ensure that everything has been delivered as expected.

For the smart contract, could you please open source the code and provide the GitHub link. At least we require that you submit the ABI to https://b32.vecha.in/.

**Review by Newman1515 — CHANGES_REQUESTED** [review]
Submit the change

**Comment by NecoSherry** [comment]
I’m closing the application due to inactivity. Let me know if I should reopen it.

**Comment by Bread-VeSea** [comment]
Apologies @NecoSherry - I've had this on my to-do for some time now and my recent attempt realized so much time had passed, and our build growing, that it was more than a simple update.

If you can re-open I aim to have it submitted within the month.

**Pull request closed without merging**
