### PR TITLE
Create PropelPixel.md

### PR DESCRIPTION
**Pull request by victorwangse**
# VeChain General Grant Application 

## Project Overview 

- Project: PropelPixel
- Team Name: PropelPixel Team
- Payment Address: USDC (ERC 20) payment address. 0xbc9b2eabfe40d2b67ea0743c92bfca8ada4ffaed

##### Project Brief

Switching to sustainable transport could reduce per capita carbon emissions by 50%. So what’s stopping us? Biking, public transit, and carpooling are simply less attractive. PropelPixel changes that. We’re building a one-of-a-kind social experience around using sustainable transit. 

We incentivize users by prompting them to take a picture every time they carpool with friends, ride the subway, and more. Users can then build and show off their virtual city with customizable NFT buildings linked to each picture they take—a new level of interactivity to the typical social media feed. The more they document and trade buildings, the more $VET they earn, which can be used to purchase products from sustainable companies partnered with PropelPixel. 

##### Benefits of Using VeChain

VeChain allows for tracking NFTs so friends can know which carpool moment each building came from. The Vechain Thor platform's quick transactions and low energy are perfect for PropelPixel's active user base and high-volume transactions. The dual-token system ensures that transaction costs are minimized and nonvolatile, and VeChain's anonymity for users keeps their speed, photo, and location data secure.

PropelPixel's target audience is young, everyday people. PropelPixel’s friendly and accessible interface will be the introduction to blockchain technology for many users. By associating the benefits of sustainable transit with VeChain's platform, users can become familiar with how blockchain works and its potential applications. Users sharing their experiences and achievements on the app fosters community and promotes VeChain. With a total addressable market of 144 million young adults and $172.8 million, PropelPixel will elevate the VeChain platform.

##### Pitch Deck
[PropelPixel_Slidedeck.pdf](https://github.com/victorwangse/grant-program/files/13048872/PropelPixel_Slidedeck.pdf)

##### One Pager
[PropelPixel_OnePager.pdf](https://github.com/victorwangse/grant-program/files/13049074/PropelPixel_OnePager.pdf)

### Project Details
 <br />

 <br />

 <br />

 <br />

 <br />

Tech Stack Overview: 
- Node.js
- Solidity
- Flutter
- Mongo.db
- REST API
- React Native

### Ecosystem Fit
Other blockchain projects have used social media to promote sustainability, such as Steemit and UpTrennd. SweatCoin implemented a similar token-earning system. However, these apps struggled to gain long-term traction because of their passive experience–users had little incentive to interact with the app on a daily basis.

PropelPixel seeks to build a community between friends who use the app to document their eco-friendly transportation experiences. The social aspect of taking and sharing pictures with friends and developing personalized cities makes PropelPixel stand out. When all of their friends are already on the app, users will be more inclined to join and stay on PropelPixel.

### Team members

- Jean Lin
- Victor Wang
- Carson Wang
- Asanshay Gupta
- Sarah Dufays

### Team's experience

Our team has a wide range of expertise and passion, with representation from institutions like MIT, Stanford, and Wharton. With 15+ years of combined experience, we've established our proficiency in app development and blockchain technology.

We have developed an eye-controlled wheelchair and created the 'Oxygen Planner', a tool that aided medical professionals during the COVID crisis. This app has since been integrated into over 2,000 hospitals in 120 countries. 

Together, we have participated in and won over 10 highly competitive nation-wide hackathons and have aligned with industry leaders like ALTEN, Google, and Microsoft. One member has worked at the Federal Reserve to research and develop Central Bank Digital Currency, and another member has been certified as one of the world’s youngest Certified Ethical Hackers. Most recently, PropelPixel was named a winner of the EasyA x Vechain hackathon.

### Team Code Repos

- https://github.com/SuperAce100
- https://github.com/sdufays

### Team LinkedIn Profiles

- https://www.linkedin.com/in/sarah-dufays/
- https://www.linkedin.com/in/asanshay/
- https://www.linkedin.com/in/carsonjwang/ 
- https://www.linkedin.com/in/jean-t-lin/
- https://www.linkedin.com/in/victor-wang-se/

#### Overview

|  | Milestone 1 | Milestone 2 | Milestone 3 | Total |
| - | - |- |- |- |
| Estimated Duration | 60 d | 60 d | 60 d | 180 d |
| Full-time equivalent (FTE) | 1 | 2 | 1 | 4 |
| Cost | $ 3,000 | $ 6,000 | $ 6,000| $ 15,000|

#### Milestone 1 — Smart Contract & Backend

| Number | Deliverable | Specification |
|-|-|-|
| 1.1| Smart Contract | We will craft smart contracts tailored for diverse NFT tasks. Our minting function ensures each NFT's uniqueness and verifiability on the blockchain. Our contracts will transparently track NFT ownership, maintaining each asset's authenticity. We'll also facilitate easy VET transfers for sponsorships and integrate image creation and indexing tools, streamlining the overall experience. |
| 1.2 | Backend | We will create a backend service with two primary functions: Sponsorship Management and User Notification. The Sponsorship Management System will facilitate initiating, tracking, and completing deals with sponsors, ensuring transparent and efficient communication. It will also periodically rotate between sponsors. The User Notification System will handle real-time alerts, allowing users to receive timely updates on deal statuses, interactions, and other platform activities. |
| 1.3 | White Paper | We will publish our white paper to introduce the market to social media for sustainability and sharing NFTs. This create-to-earn model is new to the market, so we will present our business models to the broader community before releasing our product. |

#### Milestone 2  —  Frontend & Partnership Engagement
| Number | Deliverable | Specification |
|-|-|-|
| 2.1| Alpha Testing | We will launch the Alpha version of our app to a select group of 100 users for feedback. This closed testing phase will last for three weeks, during which we'll actively solicit feedback on user experience, functionality, and potential bugs. Utilizing a dedicated feedback portal, participants can document their experiences and suggestions, ensuring that we comprehensively understand areas for improvement before the public release. |
| 2.2 | Frontend | We will design an intuitive UI/UX and integrate our app with the platforms of our eco-partners. We will prioritize a UI that reflects simplicity and clarity while ensuring that the user experience (UX) will be mapped out with a user-centric approach, providing smooth navigation, rapid loading times, and responsive design for both mobile and desktop users. |
| 2.3 | Partnerships | We will sign contracts with eco-friendly businesses targeting sectors such as renewable energy, sustainable fashion, and organic farming to partner with them for the deals on our platform. These partnerships aim to bring exclusive, eco-conscious deals to our platform's users, ensuring they benefit from sustainable options while supporting environmentally responsible businesses. |

#### Milestone 3  —  Market Launch & Marketing
| Number | Deliverable | Specification |
|-|-|-|
| 3.1| Market Launch | We will release the app to all users in the US initially. |
| 3.2 | Market Campaigns | We will create a campaign in the lead-up to the launch as well as follow the launch with exclusive promo NFTs and referral rewards to grow our customer base. |

#### Community engagement

We will publish Medium articles for all of our milestones. We will also be sharing our progress on Twitter/X @_carsonwang_ with regular updates while keeping our code open source by uploading to Github.

## Future Plans

We will maintain our relationships with partners throughout operations, periodically rotating deals while also trying to add new partners into the mix. Our ultimate long-term goal is to expand beyond the US and into other emerging/developed markets. The team hopes to make sustainable living a fun lifestyle choice for the community while growing social engagement and reducing carbon emissions from private transportation.

## Additional Information 

- What work has been done so far? <br />
We have created the first mockups for the UI (visual) and we have established our team members moving forward. 
- Are there any teams who have already contributed (financially) to the project? <br />
No
- Have you applied for other grants so far? <br />
No

### CODE REVIEW

**Comment by NecoSherry** [comment]
Thank you for application. I would like to confirm if you are planning to apply for the **Vechain-EasyA Hackathon Grant Track**. Currently, your application form and saved directory are set for the Vechain general grant. If you are indeed applying for the Vechain-EasyA Hackathon Grant Track, please make the necessary adjustments to your PR application content and directory following this link, https://github.com/vechain/grant-program/tree/master/Vechain-EasyA-Hackathon-Boston-Oct-2023.

**Comment by victorwangse** [comment]
Hi! Yes we are applying for the Vechain-EasyA Hackathon Grant Track

**Comment by NecoSherry** [comment]
> Hi! Yes we are applying for the Vechain-EasyA Hackathon Grant Track

Could you help modify your application according to the [EasyA hackathon application template](https://github.com/vechain/grant-program/blob/master/Vechain-EasyA-Hackathon-Boston-Oct-2023/applications/application-template.md), and move your application to folder [`Vechain-EasyA-Hackathon-Boston-Oct-2023/applications`](https://github.com/vechain/grant-program/tree/master/Vechain-EasyA-Hackathon-Boston-Oct-2023/applications). Thank you for your cooperation in advance!

**Comment by NecoSherry** [comment]
I am closing this pull request because there is a new one #203 to replace it.

**Pull request closed without merging**
