### PR TITLE
OpenBiSea NFT Marketplace and motoDEX NFT game

### PR DESCRIPTION
**Pull request by oleksiivinogradov**
# Grant Application Checklist

- [ ] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] An Ethereum address for the payment of the milestones is provided inside the application.  
- [ ] The total funding amount of the project is up to USD $30k for every grant applications.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] If you own an Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to grant@vechain.org to claim the additional grant.

### CODE REVIEW

**Comment by NecoSherry** [comment]
Thanks for your application.

We had a quick look and found that your application lacks many details of your project.  Leaving the website url is not enough, we need you to describe all aspects of your project in the application. It requires a higher level of detail in order to be considered for review. We encourage you to expand on it by providing more precise details in the sections Project Details and Development Roadmap. [The application template](https://github.com/vechain/grant-program/blob/master/applications/application-template.md) is a good reference as to what type of information we expect applicants to provide.

**Comment by oleksiivinogradov** [comment]
> Thanks for your application.
> 
> We had a quick look and found that your application lacks many details of your project. Leaving the website url is not enough, we need you to describe all aspects of your project in the application. It requires a higher level of detail in order to be considered for review. We encourage you to expand on it by providing more precise details in the sections Project Details and Development Roadmap. [The application template](https://github.com/vechain/grant-program/blob/master/applications/application-template.md) is a good reference as to what type of information we expect applicants to provide.

I do my best there in latest commit, but if I provide a link, there are all described in simple way. I guess basic idea for grant program isn't copy/paste ready to use materials but find good project for ecosystem?

**Comment by oleksiivinogradov** [comment]
> 

Now it looks much better in example to update. Please check latest commit, thank you for your help

**Comment by NecoSherry** [comment]
Thanks for applying to our grant program. We regret to inform you that your application has been rejected by the grant committee. After careful evaluation, it was concluded that your application missed some necessary information that made it difficult for the committee to evaluate its impact on the community. Consequently, we are closing the PR associated with your application. In any case, we thank you for your interest in the grant program.

**Pull request closed without merging**
