### PR TITLE
SaintsUndone_M2

### PR DESCRIPTION
**Pull request by Pranav9931**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Comment by Pranav9931** [comment]
Hey @NecoSherry @libotony 

We've submitted the Milestone 2 Deliverables status!
Additionally @libotony I've invited you to the repos to take a look at the codebase too.

Thanks!

**Comment by Pranav9931** [comment]
Hii @libotony @NecoSherry 
Can we get an update on our PR?

**Comment by Pranav9931** [comment]
Hii there!

When can we expect a reply or follow up on this?

**Comment by libotony** [comment]
Hi @Pranav9931, do you have a deployed version of the marketplace? I have also requested access to the design file in google drive, please approve when you are available.

**Comment by Pranav9931** [comment]
Hii @libotony 
We've approved your request for the google drive!

We can't go public yet, so we don't have a deployed version of our Marketplace!

Our team is working on the complex logic we have to sale/resale entities on our marketplace and we're integrating backend with frontend at the moment.

Thanks!

**Comment by Pranav9931** [comment]
Also, Thanks for replying back. We really appreciate your time.

**Comment by libotony** [comment]
> Hii @libotony We've approved your request for the google drive!
> 
> We can't go public yet, so we don't have a deployed version of our Marketplace!
> 
> Our team is working on the complex logic we have to sale/resale entities on our marketplace and we're integrating backend with frontend at the moment.
> 
> Thanks!

Thank you for the quick reply, the main concern is as an outside developer it is hard for me to review your code as a proof of milestone, so I would like to ask if it's possible to have a demo video of your current achievement?

**Comment by Pranav9931** [comment]
Hii @libotony 
Thanks for the reply.

We'll try to create a demo video consisting of all the elements of our product as soon as possible! May be by tomorrow.

We'll try to include all our achievements on the tech and non-tech side that'll serve as a status report as well.

Thanks!

**Comment by Pranav9931** [comment]
> Hii @libotony Thanks for the reply.
> 
> We'll try to create a demo video consisting of all the elements of our product as soon as possible! May be by tomorrow.
> 
> We'll try to include all our achievements on the tech and non-tech side that'll serve as a status report as well.
> 
> Thanks!

Hey @libotony 
We've uploaded the video to the Saints Design folder. Please take a look. You can access it via this link:
[Google Drive Link](https://drive.google.com/file/d/1-mTaxT-jeuy9HLyyci0Iiy38jPdKZB6W/view?usp=sharing)

While our primary focus is on mass-producing the physical product (the T-shirt), we're also continuing to build and rigorously test the tech side to ensure a great user experience at launch. During this phase, we'll be polishing our entire infrastructure and product.

Thanks!

**Review by dabossdana — APPROVED** [review]

**Comment by Pranav9931** [comment]
Hii @dabossdana @libotony @NecoSherry 
I'm really happy that the changes are approved.
When can we expect the next Milestone Payment?
Thanks!

**Comment by Pranav9931** [comment]
Hey @NecoSherry @libotony 
Can we get an update on this please?

Regards,
Pranav

**Review by libotony — APPROVED** [review]

**Comment by Pranav9931** [comment]
Hey @NecoSherry @libotony 
Hey! I'm happy to inform you that we are at the final stage of building our product. We are at the final production stage of our inventory, thus a remainder amount is due to be paid to the manufacturer of apparels. We expected to make payment through the final phrase grant. Since we have completed the 3rd phrase milestone, will it be possible to give a status? 
Thanks!

**Review by NecoSherry — APPROVED** [review]

**Comment by NecoSherry** [comment]
@Pranav9931  Thank you for the delivery. We will promptly proceed with the payment process for milestones 3. Before we make the payment, could you please confirm if the payment address is still the same as in your application?

**Comment by Pranav9931** [comment]
Hey @NecoSherry 
Thanks for your reply.

Yeah, we confirm that the payment address is still the same that was submitted during the Grant Application.

Regards
Pranav

**Comment by NecoSherry** [comment]
Thank you for confirming the address. The payment request has been initiated, and it will take some time to process. We appreciate your patience in advance.

**Comment by Pranav9931** [comment]
Hii @NecoSherry  
Thanks for the info 😊

**Pull request merged**
