### PR TITLE
DApp World Milestone Delivery - 2

### PR DESCRIPTION
**Pull request by ankasaw99**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Comment by ankasaw99** [comment]
I think i did wrong commit, will update it !

**Comment by NecoSherry** [comment]
I have noticed that two delivery files were submitted in the current pull request. It is my understanding that the Milestone 1 delivery file has already been successfully submitted and merged in pull request #140. Could you help remove the Milestone 1 delivery file from the current pull request, leaving only the Milestone 2 delivery file.

**Comment by ankasaw99** [comment]
Hey @NecoSherry , thank you for quick response. I have made the changes, let me know if its correct, Thank you.

**Review by mongelly — APPROVED** [review]

**Review by NecoSherry — APPROVED** [review]

**Comment by ankasaw99** [comment]
Hello, @NecoSherry @mongelly any update on the further procedure for milestone - 3 and feedback on milestone - 2

**Pull request merged**
