### PR TITLE
Add application for vechain.energy

### PR DESCRIPTION
**Pull request by ifavo**
# Grant Application Checklist
* [x]  The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
* [x]  An Ethereum address for the payment of the milestones is provided inside the application.
* [x]  The total funding amount of the project is up to USD $30k for every grant applications.
* [x]  The initial PR contains only one commit (squash if needed before submitting your PR).
* [x]  If you own an Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to [grant@vechain.org](mailto:grant@vechain.org) to claim the additional grant.

### CODE REVIEW

**Comment by NecoSherry** [comment]
Thank you for your application and your email has been received. We will look into it as soon as possible.

**Comment by NecoSherry** [comment]
Hi @ifavo  Thanks for your application. It looks great. We list a few improvements that could help to increase the chance of acceptance:

1. We did not see the Mainnet launch in your plan. We hope that vechain.energy would run in the Mainnet. Would you please add the Mainnet launch to your milestones?

2. What's the business model? How do you profit from this service and over your cost? The grant program would not pay all the cost in the furture. 

3. For the milestone 1, it seems less work and the current day rate is expensive. Could you potentially increase the scope or reduce the price? You could split the milestone1 into multiple milestones with more work to clarify that it needs 45 man-day. 

4. For the milestone 2:  
	- Would you please share more details about the server cost? 
	- Do you have a business model to profit from VeChain.energy to cover the VTHO to sponsor applications or users?

5. If you have an opeartion plan for the furture, add it to your application form.

6. We recommended that the community engagement could be improved.  Maybe you could put social medium, like Twitter, Telegram group, or Reddit, on your website. When the developers need assistance, they could get in touch with you and get help.

**Comment by ifavo** [comment]
@NecoSherry Thank you for your positive feedback! I will provide an updated version during the week.

**Comment by ifavo** [comment]
@NecoSherry I have updated the requested information, especially increased the details in the milestones.

Regarding the business model:  
While I am grateful if the grant supports the basics, the additional functionality to support a business model is not what I expect from the grant. That is why there was less information in it.

Please let me know if you require more information or if there are any questions.

**Review by mongelly — APPROVED** [review]

**Review by zzGHzz — APPROVED** [review]

**Comment by NecoSherry** [comment]
@ifavo  Congratulations! Your application has been accepted! 

We will transfer 1 USDT(ERC20) to your payment address for test. Kindly confirm the USDT (ERC 20) payment address: 0xcC4B3412161Ea88d0538D2Da15cffa74af0eE9D4.

**Comment by ifavo** [comment]
I am very happy and grateful @NecoSherry for accepting the application!

I confirm the address `0xcC4B3412161Ea88d0538D2Da15cffa74af0eE9D4` on ETH.

**Pull request merged**
