### PR TITLE
thisismagma milestone update

### PR DESCRIPTION
**Pull request by andydemeulemeester**
# Grant Application Checklist

- [ ] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] An Ethereum address for the payment of the milestones is provided inside the application.  
- [ ] The total funding amount of the project is up to USD $30k for every grant applications.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Comment by libotony** [comment]
Is this PR replacing #220? Don't forget to resolve the conflict @andydemeulemeester

**Comment by andydemeulemeester** [comment]
> Is this PR replacing #220? Don't forget to resolve the conflict @andydemeulemeester

Yes, this is replacing #220. The conflict is solved.

**Review by libotony — APPROVED** [review]

**Comment by andydemeulemeester** [comment]
@libotony are their other things that are needed to get approved by the minimum needed reviewers?

**Comment by libotony** [comment]
> @libotony are their other things that are needed to get approved by the minimum needed reviewers?

I think not, currently your delivery is in our internal process of payment, so wait patiently. We'll let you know once the process has been done.

**Comment by NecoSherry** [comment]
Thank you for the delivery. We will promptly initiate the payment process for milestones 2 and 3. If there are any updates, we will notify you by email. Thank you in advance for your patience and cooperation.

**Review by NecoSherry — APPROVED** [review]

**Pull request merged**
