### PR TITLE
Milestone 1 of the thor devkit dart

### PR DESCRIPTION
**Pull request by RsTs23**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] If you own an Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to grant@vechain.org to claim the additional grant.

### CODE REVIEW

**Review by laalaguer — DISMISSED** [review]

**Comment by RsTs23** [comment]
Sorry, I accidentally committed our next application in this pull request. Please disregard, we will create a seperate pull request for it.

**Comment by laalaguer** [comment]
Hey devs,

I have checked your source code at URL https://github.com/SayNode/thor-devkit.dart, (point me in the right direction if I am in the wrong place). Could you please provide in your project source code the developer's guide to participate in compiling and testing your project (eg. README.md to include the instructions to compile the project on Linux or reproduce the tests and able to contribute some code if deemed fit.)

This is ultra-important for the open-source community to re-run and exam the code. Thanks.

**Comment by wernerliechti** [comment]
Hey @laalaguer 

The direction is right. Usually, with Dart packages, the process is the following: You import them into your flutter project via https://pub.dev/ the official package repository for Dart and Flutter apps. There everything is explained quite well how to use the package. This page is the first one you get to know as a Flutter Dev so this should be really straightforward for everyone that wants to use our package.

Our package is also on pub.dev:
https://pub.dev/packages/thor_devkit_dart

If you have any questions, please let me know

**Comment by laalaguer** [comment]
Thanks for the fast reply!

As part of the access process, we need to compile the package locally and run tests.

Please write in the `README.md` instructions on compiling and testing on Ubuntu for the dummy Dart developers, so we can proceed with the evaluation.

**Comment by wernerliechti** [comment]
Hey @laalaguer 

Alright, we added it to the README File.  If you have any further questions, we also could schedule a short video call to answer them. I hope we solved the issue, otherwise, let us know. 

Have a nice day
Werner

**Comment by laalaguer** [comment]
Hello buddy,

We have read your README which is using VScode and a plugin to test. For official recommendation to use the `dart test` and `package:test` to do the test is recommended other than IDE. As a system package we also recommend to follow the testing guide. 

We recommend you to provide a command line interface to compile and test.
see it here: https://dart.dev/guides/testing

**Comment by RsTs23** [comment]
Hey @laalaguer

Thank you for your feedback. We updated the delivery repository according to your suggestions.

- We changed the README to reflect the new way to run the tests. Now you can run the tests using "dart test" as suggested.  
- Now you can run the tests directly in the command line and an IDE is not strictly necessary anymore.

Let us know if we need to add anything else.

Have a great day
Renato

**Comment by laalaguer** [comment]
Hi,

Although not mentioned in the README we have tried `flutter pub get` to install dependencies in your project.

Then, we tried to run the `dart test` as instructed in the README.

Please kindly point out why the tests weren't run.

```
Could not find a file named "pubspec.yaml" in "/home/user/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-44.0.0".
#0      new Pubspec.load (package:pub/src/pubspec.dart:307:7)
#1      new Package.load (package:pub/src/package.dart:128:29)
#2      SystemCache.load (package:pub/src/system_cache.dart:105:20)
#3      Entrypoint._createPackageGraph (package:pub/src/entrypoint.dart:119:63)
#4      Entrypoint.packageGraph (package:pub/src/entrypoint.dart:114:54)
#5      getExecutableForCommand (package:pub/src/executable.dart:338:19)
#6      TestCommand.run (package:dartdev/src/commands/test.dart:33:36)
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#8      DartdevRunner.runCommand (package:dartdev/dartdev.dart:231:30)
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#10     new Future.sync (dart:async/future.dart:301:31)
#11     CommandRunner.run (package:args/command_runner.dart:119:14)
#12     runDartdev (package:dartdev/dartdev.dart:66:29)
#13     main (file:///tmp/tmp3v71j61z/dart-2.17.5/dart/pkg/dartdev/bin/dartdev.dart:11:9)
#14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

```

**Comment by romme86** [comment]
> Hi,
> 
> Although not mentioned in the README we have tried `flutter pub get` to install dependencies in your project.
> 
> Then, we tried to run the `dart test` as instructed in the README.
> 
> Please kindly point out why the tests weren't run.
> 
> ```
> Could not find a file named "pubspec.yaml" in "/home/user/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-44.0.0".
> #0      new Pubspec.load (package:pub/src/pubspec.dart:307:7)
> #1      new Package.load (package:pub/src/package.dart:128:29)
> #2      SystemCache.load (package:pub/src/system_cache.dart:105:20)
> #3      Entrypoint._createPackageGraph (package:pub/src/entrypoint.dart:119:63)
> #4      Entrypoint.packageGraph (package:pub/src/entrypoint.dart:114:54)
> #5      getExecutableForCommand (package:pub/src/executable.dart:338:19)
> #6      TestCommand.run (package:dartdev/src/commands/test.dart:33:36)
> #7      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
> #8      DartdevRunner.runCommand (package:dartdev/dartdev.dart:231:30)
> #9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
> #10     new Future.sync (dart:async/future.dart:301:31)
> #11     CommandRunner.run (package:args/command_runner.dart:119:14)
> #12     runDartdev (package:dartdev/dartdev.dart:66:29)
> #13     main (file:///tmp/tmp3v71j61z/dart-2.17.5/dart/pkg/dartdev/bin/dartdev.dart:11:9)
> #14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:32)
> #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
> ```

Hi @laalaguer , I think you are running the `dart test` command in the __flutter__ project root. You shall run the tests in the root of the __cloned__ project instead. I added more details and updated the __README.md__, so you shall find the new instructions in the home of the project [https://github.com/SayNode/thor-devkit.dart/tree/main/thor_devkit_dart](https://github.com/SayNode/thor-devkit.dart/tree/main/thor_devkit_dart).

Thank you for this feedback, please let me know if you can get through a test run with the updated docs!

**Comment by laalaguer** [comment]
> Could not find a file named "pubspec.yaml" in "/home/user/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-44.0.0".
> #0      new Pubspec.load (package:pub/src/pubspec.dart:307:7)
> #1      new Package.load (package:pub/src/package.dart:128:29)
> #2      SystemCache.load (package:pub/src/system_cache.dart:105:20)
> #3      Entrypoint._createPackageGraph (package:pub/src/entrypoint.dart:119:63)
> #4      Entrypoint.packageGraph (package:pub/src/entrypoint.dart:114:54)
> #5      getExecutableForCommand (package:pub/src/executable.dart:338:19)
> #6      TestCommand.run (package:dartdev/src/commands/test.dart:33:36)
> #7      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
> #8      DartdevRunner.runCommand (package:dartdev/dartdev.dart:231:30)
> #9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
> #10     new Future.sync (dart:async/future.dart:301:31)
> #11     CommandRunner.run (package:args/command_runner.dart:119:14)
> #12     runDartdev (package:dartdev/dartdev.dart:66:29)
> #13     main (file:///tmp/tmp3v71j61z/dart-2.17.5/dart/pkg/dartdev/bin/dartdev.dart:11:9)
> #14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:32)
> #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

Hi, 

First of all, I love your project totally, and I would 100% love to pass the milestone check.

I tried this and made 100% sure I am in the right folder deep down and run the same command (But I am on an Ubuntu system I suspect it won't harm the compile anyway). 

Shall we schedule a quick TG chat and let's solve this problem quickly? I am sure you are expecting this fund!

**Comment by RsTs23** [comment]
Hi @laalaguer 

We found and fixed the issue on Ubuntu. The issue was an uused library that caused some trouble. We updated the repository. `dart test` should now run as expected.

**Review by laalaguer — APPROVED** [review]

**Review by NecoSherry — APPROVED** [review]

**Pull request merged**
