### PR TITLE
Seer oracle application

### PR DESCRIPTION
**Pull request by vebank**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] If you own an Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to grant@vechain.org to claim the additional grant.

### CODE REVIEW

**Comment by laalaguer** [comment]
Hello devs,

Before we have a total rating of the application, we have several concerns:

1) Would you open-source any code. Eg. the most concerning part this the "sucking CEX/DEX price" part. Would you open-source them so it can enhance the possibility of passing the application.

2) The source of the CEX/DEX prices. We can't help but noticed 7 sources of the pricing feed: 

| 1 | Binance |
| 2 | CoinBase |
| 3 | Kraken |
| 4 | Gemini |
| 5 | Poloniex |
| 6 | Kraken Crypto Watch |
| 7 | Vexchange |

However, eg. We are NOT traded on the Kraken/Coinbase. But the top 3 largest CEX trading source is Binance, Kucoin, Huobi, and the latter two are not mentioned on the list of the sources. On the DEX side, we have noticed that VeRocket is traded at a higher volume daily than Vexchange. So help us explain your selection criteria of source.

3) Your doc center of "Documentation of core components, protocols, architecture, etc. to be deployed: https://docs.vebank.io/welcome." metioned in your article isn't well documented about the protocols and formulas, could you kindly add some?

4) The milestones sections aren't fully documented. So we would like you to have a clear view of the spending of $30k * 1.5

**Comment by vmtram** [comment]
Thanks a ton for your quick feedback, @laalaguer . We would love to address your questions as follows:

1. We are going to make public all the source codes which include, but not limited to: smart-contracts, back-ends (logic), crawlers, and the front-ends available at: https://github.com/seer-oracle

2. The answer is yes. We had some internal discussions with the team about the rationale behind the existing exchange price feeds as well as vision of Seer Oracle, and confirmed that we would be incorporating additional exchange price feeds to Seer oracles the next release version of Seer 1.1. The reason we are not listing them here is because they do not fall within the scope of this application pertaining only to Seer v1.0, and require the next round of grants/fund raising to implement.

In the short term, Seer Oracle will be upgraded to list CEX and get price feeds from Kucoin, Houbi for VET.

On the DEX side, we are using Vexchange because it has the APIs to pull asset prices for all assets supported on the platform. Towards that end, VeRocket only provides APIs to get VET price. Your notes are really appreciated for us to plan the next step to consider VeRocket due to its competitive outlooks in terms of transaction volume.

On the Alts side, we totally agree that BitMart, OceanEx are excellent resources of tokens on VeChain. In this current version, Seer Oracle only focuses on VET, VTHO, ETH, BTC price in the first launch. On that note, Seer Oracle continues to feed more data, not only asset prices but also other on-chain information.

3. We have committed the documents for Seer Oracle details at: https://github.com/seer-oracle/smc-price-oracle/blob/master/Technical_document_v1.0.md
4. We have committed new updates on our milestones which include additional details regarding grant allocation.
We would like to clarify on Checked Economic X Node - if that is what you referred to as “$30k x 1.5”. Currently we do not plan on running any Economic X Nodes on VeChain for Seer Oracles v1.0.

**Comment by laalaguer** [comment]
Thanks for the quick modification and clarification. The application reads smoother now. The team will discuss the details of the materials received. Meanwhile, you can join the dev channel on TG (https://t.me/VeChainDevCommunity) to have a chat.

**Comment by NecoSherry** [comment]
Thanks for updating the application. We have discussed the modification and have follow-up questions: 

1. It's mentioned in your application that

>  SEER provides real-time data feeds of 10+ key asset prices: BTC, ETH, VET, VTHO, VeUSD, and more, ensuring every dApps on VeChain networks can easily access reliable and trustworthy datasource.

But we didn't find more details about how other dApps use the data. By the open source code, or you will provide an oracle service so that others in the ecosystem could use Seer oracle? It would be better if Seer oracle provided a public service that would be useful for others in our ecosystem and could be reused by them for their projects. 

2. About the choice of CEX/DEX, we recommend Seer 1.0 involve Kucoin, Houbi, BitMart and OceanEx. They have more impact on our ecosystem and are our priority. It will increase the opportunity to be accepted. 

3. For the milestones, it seems less work and the current day rate is expensive. Could you potentially reduce the price or increase the scope?

**Comment by vebank** [comment]
Hi @NecoSherry , we commit the changes and the update for detail as the below:

1. We are both open source code at https://github.com/seer-oracle and provide oracle data for builders without any fee. The guideline how to use Seer oracle data for other builders on VeChain at: https://github.com/seer-oracle/smc-price-oracle/blob/master/Technical_document_v1.0.md

2. We add more exchanges as your recommendation for assets price at https://github.com/seer-oracle/crawler-api/commit/14190915b44031fecd9be8c5835c70e7842a39b6?diff=split#diff-7ef7996221cfdb71c1e41136ee26135e29687aac3c83672f232fd91cf583bb40
and https://github.com/seer-oracle/calculate-node-job/commit/b8feb8e1761d93b001b72c09edd728edf596945e

3. We share more information about the roadmap and milestones for Seer oracle at #87 
Additionally, for the mainnet deployment, we need around $10K in $VTHO to pay for gas fees and $6K to pay for several nodes (server) to keep running at least 12 months, so that is why it will affect a lot in our fund allocation.

**Comment by vebank** [comment]
Hello @NecoSherry @laalaguer , hope the review process is good. We want to notify you that we have added more detail about the price Deviation Threshold at [Technical_document_v1.0.md](https://github.com/seer-oracle/smc-price-oracle/blob/master/Technical_document_v1.0.md#2-architecture)
Thanks.

**Comment by NecoSherry** [comment]
Hi @vebank Thanks for applying to our grant program. Unfortunately, your application has not been accepted. The grant committee would appreciate a decentralized solution to oracles as well as a more reasonable budget plan. 
I’m therefore closing the PR.

**Pull request closed without merging**
