### PR TITLE
VeChain Grant Proposal - Tali AI 

### PR DESCRIPTION
**Pull request by niznet89**
Create tali_ai.md

# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Comment by niznet89** [comment]
Hey @laalaguer - let me know if you need any additional info or would like to jump on a call to discuss the application!

**Comment by laalaguer** [comment]
> Hey @laalaguer - let me know if you need any additional info or would like to jump on a call to discuss the application!

Cool. This task is assigned to me. Could you please send me an email to join the test of this test? laalaguer@gmail.com

**Comment by laalaguer** [comment]
Thanks for the application. Going into committee review.

**Comment by NecoSherry** [comment]
Thank you for your interest in our grant program and for submitting your application. We regret to inform you that your application has been rejected by the grant committee. During the evaluation process, we carefully reviewed your project details and tested the demo provided. However, the demo had numerous errors during the test. 

I'm therefore closing the PR.  In any case, thank you for your interest in the grant program.

**Pull request closed without merging**
