### PR TITLE
FibreTag M3 Delivery

### PR DESCRIPTION
**Pull request by jjjutla**
# FibreTag M3 Delivery

Initial PR: https://github.com/vechain/grant-program/pull/195

Milestone 3 Deliverable: https://github.com/jjjutla/FibreTag/blob/main/fibretag-3.md

### CODE REVIEW

**Review by NecoSherry — CHANGES_REQUESTED** [review]
You have already submitted the milestone 2 delivery. Could you please remove the milestone 2 delivery file from this pull request?

**Comment by jjjutla** [comment]
It's now corrected.

There was a mistake in the commit for M2 which carried over into this PR

**Comment by jjjutla** [comment]
@NecoSherry @libotony Has there been any update on the feedback for M3, we are almost completed with M4 and waiting for launch, thanks

**Review by libotony — APPROVED** [review]

**Review by NecoSherry — APPROVED** [review]

**Comment by NecoSherry** [comment]
Thank you for delivering milestone 3. We will promptly proceed with the payment process for milestones 4. Before we make the payment, could you please confirm if the payment address is still the same as in your application?

**Comment by jjjutla** [comment]
Thanks, yes I can confirm it's the same

**Comment by NecoSherry** [comment]
@jjjutla  Thank you for confirming the address. The payment request has been initiated, and it will take some time to process. We appreciate your patience in advance.

**Comment by jjjutla** [comment]
@NecoSherry Do you have any update on the payment, we are almost completed with the next milestone and still waiting for payment.

**Pull request merged**
