### PR TITLE
Add application for VOTEOS

### PR DESCRIPTION
**Pull request by DaniilBabanin**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] If you own an Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to grant@vechain.org to claim the additional grant.

### CODE REVIEW

**Comment by NecoSherry** [comment]
Hi @DaniilBabanin, thanks for your application. We had a quick look and there are some questions:

1. Some pictures are missing in your application. Could you please update it?
2. Do you have a plan to open source some parts of the project? If you have, please mentioned in your application.
3. What is your furture plan for promotion? 
4. The deliverables of the milestones in your roadmap is mainly features for your system. How could we review and test the deliverables? Could you fill in deliverables which could be verified in the "Column Deliverables" and list the features or functionality in the "Column Specification". 

Do you mind updating your application to make the questions clear? Thank you very much for your cooperation and updating in advance.

**Comment by NecoSherry** [comment]
Hi, thanks for your update. We have discussed about your application and have much interest in your project. For fitter with our ecosystem, we have some comments, which will enhance the chance of being accepted:

1. It's mentioned that your audience includes all groups that, for reasons of civil or commercial law, are required to perform and document legally compliant votings. Could you make anyone create polls for others to vote in VOTEOS? We would like to fund applications that could be used by others in the ecosystem, not only for some companies. So that every single person or any organization in the community could use VOTEOS.

2. Users in VOTEOS sign up/-in with web3auth for hosted wallets. It seems that web3auth doesn't support [Connex](https://github.com/vechain/connex) . How the community sign in through VeChainThor wallet/[Sync2](https://sync.vecha.in/)? It’s required to support Connex. We recommend that the voters could sign in and vote with our wallet.

3. We have tried https://admin.voteos.com/  and noticed that the account would be assigned an address after sign in with social account. How could the users vote with their own account that already exists?

4. Could you please consider to open source the smart contract? It is ok that you do not want to open source the frontend and the backend. We recommend the smart contract open source. This will make the VOTEOS more transparent in fairness of vote.

**Comment by DaniilBabanin** [comment]
Hi, we very much appreciate your interest in our application. After discussing your feedback with our team I can say that:

1. Yes, anyone can sign up and use the application in full.
1. At the time being and for the sake of convenience we will only be able to support web3auth wallets. Otherwise, organizers would have to sign every change on the contract with an external wallet. Our goal is to keep the entry barrier for users without blockchain experience as low as possible. Allowing the use of external wallets is on our roadmap for the future, but with regard to our time-to-market goals, it will not be part of our initial release.
1. The ballot itself is an NFT token and ownership can be transferred. A vote can be transferred between voters and transfers the right to vote for every poll during an Election. Currently, transfers take place to a web3auth wallet when logging in by email.
1. After we have had the smart contracts checked by external security auditors, we intend to open-source them. Thus we can continue to increase trust in our system and look forward to further audits from the community.

**Comment by DaniilBabanin** [comment]
Hi @NecoSherry  

Can you provide an update on the current status of the grant application for the VOTEOS project?
It appears that the application had the status of "ready for review" for a while, and I was wondering if applications are still being reviewed?

It would be helpful to know if any additional information or documentation is required and if there is a timeline for when it will be reviewed.

**Comment by NecoSherry** [comment]
Thanks for applying to our grant program. It is unfortunate that your application has been rejected by the grant committee. The application is well prepared and we appreciate the efforts of the applicants. The committee is interested in your project. We consider a voting platform important to the community in our ecosystem. We would strongly recommend you to resubmit a revised application if you could improve your design to make it suitable for community use.

I’m therefore closing the PR.  In any case, we thank you for your interest in the grant program.

**Pull request closed without merging**
