### PR TITLE
Initial VeSayNode commit

### PR DESCRIPTION
**Pull request by RsTs23**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] If you own an Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to grant@vechain.org to claim the additional grant.

### CODE REVIEW

**Comment by NecoSherry** [comment]
Hey @RsTs23 , thank you for the submission,
Before we can start, we would like to engage you with several questions concern the application:

1. Centralization
As we understand, your solution is based on an open source library, web3-gear. Which requires users to store the private key inside. In your solution, it takes one step ahead and have private keys stored upon the server. This raise a concern that this tool isn’t passing beyond the "development" phase for developers and move to "production" phase. And further more, what’s the advantage of it, given that https://github.com/zzGHzz/web3-providers-connex is open source and locally available?


2. Media Pushing
We can understand it is used in-house as your solution. Our question is how is it benefit the eco-system and as "After the project is completed, an article will be created for Medium to inform developers" isn’t enough to propel the project into the big ocean. What’s your more resource input to push this project?


3. Monetization
As much discussed in the above two entries, we have gathered an opinion that it is a dev tool which most likely rely on the foundation’s "continuous" funding as operation costs. We can understand that it is meaningful for your in-house development, however, how are you planning to make money off the users? What’s your competitors and what your advantage?

**Review by Newman1515 — CHANGES_REQUESTED** [review]
Submit shange

**Comment by RsTs23** [comment]
Hey, thank you for your feedback and for checking our submission. We adjusted a couple of things to provide an answer for your question. 

First of all it's important to mention, that the application was planned as a two part submission. The second part wasn't ready yet but we created a new PR for it now here: https://github.com/vechain/grant-program/pull/75

1. Centralization: First of all: yes, your understanding is correct, we aim to provide the functionality of web3-gear. We realized that when people that are familiar with web3 development but not with VeChain start out developing it often takes quite a bit of time to get everything set up the way we need to to start working. It can easily take half a day up to a day for someone without guidance to get everything up and running (documentation is sometimes lacking and there are some dependencies, python versions and packages that need to be configured manually to get it to run). Our goal is to make this much more user friendly and provide developers the way to interact with VeChain just like they would with Ethereum and Infura. This way new developers could simply sign up, create an account and get going. Web3-providers-connex is nice and useful but it still doesn't provide the user with a direct connection from truffle and scalable service like our solution would provide. The centralization is a valid point but we can minimize the impact of it by integrating the existing VeChain wallets and giving the user the option on where to store the keys. In general this is a problem that exists with every comparable service that sacrifices decentralization for ease of use. 

2. Media Pushing: We address this in more detail in our second grant: https://github.com/vechain/grant-program/pull/75 The strategy will consist of a micture of targeted paid ads and organic growth through outrech on relevant channels.

3. Monetization: This is also addressed in the second application: https://github.com/vechain/grant-program/pull/75 We included a milestone for covering the launch and operating costs. But over the long term the goal is of course to be self sustaining. Here again we adopt a similar business model to Infura (and with the IPFS integration also pinning services like Pinata) to cover our costs. Rate limited APIs and subscription plans are the main way to montetize this service. We of course hope to grow the attractiveness of VeChain for other developers and believe that the interest in VeChain will rise in the coming months. Even if the number of developers and services running on VeChain right now might not justify the creation of the plattform, we believe there will be developers joining the community once the barriers to entry are lowered. We are in the "growth phase" after all :)

**Comment by NecoSherry** [comment]
Hi Rsts, thanks for submitting an application to our grant program.  It is unfortunate that your application has been rejected by the grant committee. 

The main reason is that we already have open source tool "[web3-providers-connex](https://github.com/zzGHzz/web3-providers-connex)" with the same function. If you want to work on a more decentralized system or a public service, it might potentially better fit in the scope of our grant program.

I’m closing the PR.  In any case, we thank you for your interest in the grant program.

**Pull request closed without merging**
