### PR TITLE
sozo_infashion.md

### PR DESCRIPTION
**Pull request by Zibilicious**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Comment by libotony** [comment]
Please adjust your application to align with the [EasyA Grant Track template](https://github.com/vechain/grant-program/blob/90ca36f2c30758b4690ceaf9ff3ef9da9f4363fa/Vechain-EasyA-Hackathon-Boston-Oct-2023/applications/FibreTag.md)

**Comment by Zibilicious** [comment]
@libotony Hi! We've reviewed our application along with the EasyA Grant Track template and aligned it to the best of our abilities. Can you point out specifically what should be updated to be aligned so I can update it right away? Thank you for your help!

**Comment by libotony** [comment]
> @libotony Hi! We've reviewed our application along with the EasyA Grant Track template and aligned it to the best of our abilities. Can you point out specifically what should be updated to be aligned so I can update it right away? Thank you for your help!

Please take a look at this [link](https://github.com/vechain/grant-program/tree/master/Vechain-EasyA-Hackathon-Boston-Oct-2023#application-process), make sure your application is located at folder `Vechain-EasyA-Hackathon-Boston-Oct-2023`.

**Comment by Zibilicious** [comment]
@libotony Hi! I've moved the application is located at the correct folder. Please review, thank you!

**Comment by libotony** [comment]
@Zibilicious, it appears that there are two application files in your submission. Please ensure that each request contains only one application. Additionally, could you incorporate the contents of `API Documentation.md` into your application file?

**Comment by Zibilicious** [comment]
@libotony Hello, we've removed the redundant application files and now there is only one. We've also deleted the API documentation file link and updated the link in the Sozo inFashion file to point to its own repository.

**Comment by libotony** [comment]
> @libotony Hello, we've removed the redundant application files and now there is only one. We've also deleted the API documentation file link and updated the link in the Sozo inFashion file to point to its own repository.
> 
> Please let me know if anything else needs to be changed, thank you!

Thank you for the update. The application has been forwarded to the review committee for final evaluation. Please bear with us; we'll provide updates as they come.

**Comment by NecoSherry** [comment]
Congratulations! Your application has been accepted by the review panel.

Before making the payment of M1, we kindly request you to confirm if your address can receive USDC (ERC-20).
Additionally, we will communicate payment details with you via email. Please **DO NOT** leave your email in the application. Instead, send an email to [grant@vechain.org](mailto:grant@vechain.org) including your project name, PR link, and the payment address (which should match the one provided in your application).

**Review by NecoSherry — APPROVED** [review]

**Comment by Zibilicious** [comment]
@NecoSherry Thank you! I have sent an email with the necessary information to the email grant@vechain.org

**Pull request merged**
