### PR TITLE
Add application for a "Cross-Chain-Token-Payment-Gateway"

### PR DESCRIPTION
**Pull request by ifavo**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Comment by ifavo** [comment]
@NecoSherry May I note that the tag:

Bildschirmfoto 2023-07-31 um 09 01 42

… `peview` may have a typo in it. It might be either `preliminary review` or `preliminary preview` :-)

**Comment by laalaguer** [comment]
In general very good application. 

Three things:

1. Since it consists of multi-chain and multi-parts, do you have some kind of audit report to ensure the system?
2. Any separation of on-chain and off-chain parts of the system? Which is on which is off?
3. If the system will be in general close source or open source?

Thanks!

**Comment by ifavo** [comment]
@laalaguer Thank you a lot for your feedback! The system is a lot simpler than it may sound at first. Its not an implementation of a bridge, its simply a structured process with some extensions to embed centralized swapping providers into the ecosytem, like changelly.

1. The cross-chain-elements are not self-made but existing centralized swapping structures will be used. The responsibility is feeding their systems and managing the output of VET.
2. On-chain is the tracking of the payments on Vechains side. Off-chain is the input channel from the third party provider used to fulfill the swaps. Communication with the provider and tracking its status is done off-chain, information is logged on-chain in certain situations (success/failure).
3. I am happy to make the on-chain-party open source in a GitHub repository. The off-chain-communication will stay closed.

**Comment by NecoSherry** [comment]
Thank you for your interest in our grant program and for submitting your application. We regret to inform you that your application has been rejected by the grant committee. 

The primary reason for this decision is that this project is centralized and has some risks in the swap process. 
I’m therefore closing the PR.  In any case, we thank you for your interest in the grant program.

**Pull request closed without merging**
