### PR TITLE
NFT Moon Metaverse

### PR DESCRIPTION
**Pull request by nftmoonmetaverse**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] If you own an Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to grant@vechain.org to claim the additional grant.

### CODE REVIEW

**Comment by NecoSherry** [comment]
Hi there, thanks for your application. We had a quick look and it looks great. 

We have found that it requires more technical details about integration of VeChain. Wallets in your project (Metamask, WalletConnect) do not support VeChain. Could you please provide more precise specification/technical details about development on VeChain? Also, how you will integrate VeChain tools and features (e.g., Sync2/Connex, fee delegation protocols, MTT, etc)?

For the milestones, once the application is accepted, the payment for the first milestone will be immediately disbursed to fund the project. We found that your application had only one milestone. We usually try to lower the risk (not the monetary one, but the risk of misunderstandings and disputes) by asking for small milestones, so that feedback and conversations happen along the way. We recommend you restructure the roadmap and split your milestone. Note that deliverables should be tangible and could be verified.

We are very interested in open source development that could be reused by others in the ecosystem. If you have any code or smart contract open source, please add it to your application.

Let us know as soon as you're done with your changes, and we'll give your application another look.

**Comment by nftmoonmetaverse** [comment]
> 
Hello. We have made changes. Here is the link https://github.com/nftmoonmetaverse/grant-program/blob/master/applications/nft-moon-metaverse-M2.md

**Comment by NecoSherry** [comment]
Hi, thanks for your quick response. We had a discussion about your application and have some comments:

1. Work related with VeChain development should be more specific. Now we could not find related information in the section "**Project Details**". 
2. For the cost and workload: Milestone 1 needs 30 FTE 16 days, and the cost is $25,000. Milestone 2 needs 24 FTE 12 days, but the cost is $5,000. The costs do not match the workload. Could you please double check your math and update the table? 
3. Once the application is accepted, the payment for the first milestone will be immediately disbursed to fund the project. We usually do not fund most of the total cost of an application for M1. On the other hand, most accepted and completed projects have 3-5 milestones by far. Smaller milestones will have higher opportunity to get accepted by the grant committee. So we recommend you to restructure your roadmap.
4. For milestone 1:
    - We ask for smart contracts developed on VeChain could be open source, at least we require to upload smart contract ABI to [B32](https://github.com/vechain/b32). 
    - It’s listed in your deliverable that you will set up the VeChain Node with validators. We need you to add receipt/invoice for server as a deliverable.
5. For milestone 2, could you update the deliverables to provide a user guide or a demo video for the features you will develop? It will help the reviewers and others in the community to verify the implement of the features. You could provide the user guide or demo video on the help center in your website and the deliverable could be the links.
6. You have created two files in this PR. Could you please just leave one?

**Comment by nftmoonmetaverse** [comment]
> 

Hello. Thanks for the recommendations. We have changed and supplemented some points based on your comments. https://github.com/nftmoonmetaverse/grant-program/blob/master/applications/nft-moon-metaverse-M2.md

**Comment by NecoSherry** [comment]
Sorry for the late reply and thanks for your update. 

The work that will be done for the development of VeChain, which you updated, should be added to the milestone table as deliverables and we need you to write in the specification that you will upload the smart contract ABI to [B32](https://github.com/vechain/b32) for the reviewers to review.

As we said in the last comment, smaller milestones will have higher opportunity to get accepted by the grant committee. Your first milestone is still too large. It contains heavy workload and the cost is high. We usually try to lower the risk (not the monetary one, but the risk of misunderstandings and disputes) by asking for small milestones, so that feedback and conversations happen along the way. Could you please divide the first milestone into smaller parts and split the cost?

For your update on GitHub, there are still two files in your pull request, please only keep one. And could you squash your commits before submitting your update? It will be more convenient to review if each update contains only one commit.

Thanks for your cooperation and looking forward to your reply.

**Comment by nftmoonmetaverse** [comment]
> Sorry for the late reply and thanks for your update.
> 
> The work that will be done for the development of VeChain, which you updated, should be added to the milestone table as deliverables and we need you to write in the specification that you will upload the smart contract ABI to [B32](https://github.com/vechain/b32) for the reviewers to review.
> 
> As we said in the last comment, smaller milestones will have higher opportunity to get accepted by the grant committee. Your first milestone is still too large. It contains heavy workload and the cost is high. We usually try to lower the risk (not the monetary one, but the risk of misunderstandings and disputes) by asking for small milestones, so that feedback and conversations happen along the way. Could you please divide the first milestone into smaller parts and split the cost?
> 
> For your update on GitHub, there are still two files in your pull request, please only keep one. And could you squash your commits before submitting your update? It will be more convenient to review if each update contains only one commit.
> 
> Thanks for your cooperation and looking forward to your reply.

Hello. Thanks for the recommendations. We have made edits to https://github.com/nftmoonmetaverse/grant-program/blob/master/applications/nft-moon-metaverse-M2.md . We also deleted one file for extraction.

**Comment by NecoSherry** [comment]
Thanks for applying to our grant program. It is unfortunate that your application has been rejected by the grant committee. It is due to the fact that the proposed work is mainly about the integration with VeChain and XP.Network, and the budget is considered unjustified. Moreover, there is no operation plan provided for the future on VeChain. 

I’m therefore closing the PR.  In any case, we thank you for your interest in the grant program.

**Pull request closed without merging**
