### PR TITLE
added SW3 grant application

### PR DESCRIPTION
**Pull request by guyett92**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Comment by libotony** [comment]
We appreciate your grant proposal and would like to provide feedback to help you further improve your project. We have two recommendations that we believe will contribute to the success of your proposal:

1. Submission of Mockup: To gain a better understanding of your project’s visual representation and user interface, we suggest submitting a mockup. A mockup will enable us to visualize the design elements and functionalities you plan to incorporate. Including a mockup will allow us to provide more precise feedback and ensure alignment with your vision. Please consider including this in your project documentation.
2. Detailed Milestone Delivery Description: While reviewing your grant application, we noticed that the milestone descriptions can benefit from more comprehensive information. We recommend providing a detailed breakdown of each milestone, including the specific tasks, deliverables, and timelines. This will help us assess the feasibility and progress of your project more effectively. By clarifying the expected outcomes and deadlines for each milestone, you will establish a clear roadmap for the successful execution of your project.

We hope you find these suggestions valuable in refining your grant proposal.

**Comment by libotony** [comment]
> Thanks @libotony - Added link to mockups and made some updates to the milestones. I'm happy to share links to the project management tool we'll be using so you can follow along the journey!

Thank you for the update, thank you for proposing to share project management details with us but I think the current material is enough for us to evaluate your project.

**Comment by NecoSherry** [comment]
The application has entered the committee review stage.

**Comment by NecoSherry** [comment]
Thank you for your interest in our grant program and for submitting your application. We regret to inform you that your application has been rejected by the grant committee. 

The primary reason for this decision is the lack of sufficient details in the project details. The plan and materials you provided make it hard to evaluate the potential business model and profitability. 

I’m therefore closing the PR.  In any case, we thank you for your interest in the grant program.

**Pull request closed without merging**
