### PR TITLE
feat/add super-nft.md

### PR DESCRIPTION
**Pull request by leeduckgo**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [NA] If you own an Economic Node or Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to grant@vechain.org to claim the additional grant.

### CODE REVIEW

**Comment by NecoSherry** [comment]
@leeduckgo Thank you for your application, we have following suggestions:

1. It would be great to add VeChain matching features to your project, such as wallet selection for users, fee delegation service (similar to MetaTransaction in Ethereum) or multi-clause transactions.  This would be valuable when evaluating applications.

2. Update each milestone with clearly delivery, such as demos (running on the VeChainThor Testnet). This would be helpful for us to evaluate the budget.

3. We will pay more attention to the future operation plan of the project when evaluating applications, please update the milestones with an operation plan in the application if you have one. The operation plan determines the significance of the project for VeChain Foundation.

4. The budget and milestones should be more detailed. The number of milestones are not limited to two, and the cost assignment should be more detailed. It is better to match the budget with the manpower, duration and delivery.

**Comment by leeduckgo** [comment]
> @leeduckgo Thank you for your application, we have following suggestions:
> 
> 1. It would be great to add VeChain matching features to your project, such as wallet selection for users, fee delegation service (similar to MetaTransaction in Ethereum) or multi-clause transactions.  This would be valuable when evaluating applications.
> 2. Update each milestone with clearly delivery, such as demos (running on the VeChainThor Testnet). This would be helpful for us to evaluate the budget.
> 3. We will pay more attention to the future operation plan of the project when evaluating applications, please update the milestones with an operation plan in the application if you have one. The operation plan determines the significance of the project for VeChain Foundation.
> 4. The budget and milestones should be more detailed. The number of milestones are not limited to two, and the cost assignment should be more detailed. It is better to match the budget with the manpower, duration and delivery.

Got It,Thx a lot. We will update our Project later.

**Comment by leeduckgo** [comment]
> @leeduckgo Thank you for your application, we have following suggestions:
> 
> 1. It would be great to add VeChain matching features to your project, such as wallet selection for users, fee delegation service (similar to MetaTransaction in Ethereum) or multi-clause transactions.  This would be valuable when evaluating applications.
> 2. Update each milestone with clearly delivery, such as demos (running on the VeChainThor Testnet). This would be helpful for us to evaluate the budget.
> 3. We will pay more attention to the future operation plan of the project when evaluating applications, please update the milestones with an operation plan in the application if you have one. The operation plan determines the significance of the project for VeChain Foundation.
> 4. The budget and milestones should be more detailed. The number of milestones are not limited to two, and the cost assignment should be more detailed. It is better to match the budget with the manpower, duration and delivery.

Updated document yet.

**Comment by NecoSherry** [comment]
Hi, @leeduckgo. Thank you for submitting an application to our grant program. It is unfortunate that your application has been rejected by the grant committee. The following are the main reasons your application was rejected:

1. The overall business logic of the project is not sufficiently clarified, which makes it difficult to evaluate the value and impact of the project to our ecosystem.
2. The description of "milestones" lacks clarity and the budget is not justifiable. 
3. The application doesn't include sufficient information about how the project would be run in future.

**Pull request closed without merging**
