### PR TITLE
Add application for node*vechain.energy

### PR DESCRIPTION
**Pull request by ifavo**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] If you own an Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to grant@vechain.org to claim the additional grant.

### CODE REVIEW

**Comment by NecoSherry** [comment]
Hi @ifavo , thanks for your application! This looks great and could be useful to the community! 

While the specification for Additional Costs is highly detailed, you don't provide that for Dedicated Server , Rotational-Node and Maintenance. Could you please describe more details about these three milestones? According to the current deliverables and specifications, the price for the three milestones seems expensive. Could you reduce the cost or expand the specification of the three miletsones?

**Comment by ifavo** [comment]
@NecoSherry thank you for your feedback!

I tried to keep the milestone deliverables short because the the project details contains the information in detail.

- For dedicated servers the ordering, setup and testing is done as described in `2x Servers`
- For Rotational-Node the development, testing and deployment is done as describe in `Node-Rotation`
- Maintenance is describe also in `Maintenance` in the project details and seems high because its 5 hours for 24 months

Is this information missing more or should I move the information to the milestone deliverables instead?

Thank you!

**Comment by NecoSherry** [comment]
Thanks for your update. 
The price is still very high according to the current workload. We recommend you refer to the price of [VeBlocks](https://github.com/vechain/grant-program/blob/master/applications/VeBlocks_upgrade.md) and reduce the price. [VeBlocks](https://github.com/vechain/grant-program/blob/master/applications/VeBlocks_upgrade.md) is also an application for running and maintenance nodes. There is risk that the application may be rejected if the price is too high. If you provide additional services, the price can be appropriately higher than the average.

**Comment by NecoSherry** [comment]
Hi @ifavo Congratulations! Your application has been accepted by the committee! 

We have recently updated our payment currency to USDC (ERC 20). Therefore we would kindly ask you to update the payment address in your application form to USDC(ERC 20) accordingly. We will perform a small test payment before the first payment.

In order to proceed with further payments, we need to contact you by email. Please send an email to grant@vechain.org with your project name, PR link and new payment address (same as in the PR). 

We look forward to hearing from you.

**Comment by ifavo** [comment]
@NecoSherry Thank you a lot for trusting me with this!

I have sent an email that the address will not change for USDC.

**Review by NecoSherry — APPROVED** [review]

**Review by libotony — APPROVED** [review]

**Review by libotony — APPROVED** [review]

**Pull request merged**
