### PR TITLE
VeChain grant research proposal

### PR DESCRIPTION
**Pull request by jgophd**
# Grant Application Checklist

- [X ] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [X] An Ethereum address for the payment of the milestones is provided inside the application.  
- [X] The total funding amount of the project is up to USD $30k for every grant applications.
- [X] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] If you own an Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to grant@vechain.org to claim the additional grant.

### CODE REVIEW

**Comment by zzGHzz** [comment]
Please respond to an email sent from peter.zhou@vechain.org to justin.goldston@sydtek.ai. Thanks.

**Comment by jgophd** [comment]
@zzGHzz, I responded to Peter and have made the requested changes to the proposal.

**Comment by NecoSherry** [comment]
Hi @jgophd  

Congratulations! Your application has been accepted!  I read from your development roadmap that you would like to be paid in USDC, and the total cost of 3 milestones is 30,750 (15,600+14,000+1,150). We only fund in USDT and the amount is up to 30,000. Could you please help us modify the application to meet this requirement?

**Comment by jgophd** [comment]
> Hi @jgophd
> 
> Congratulations! Your application has been accepted! I read from your development roadmap that you would like to be paid in USDC, and the total cost of 3 milestones is 30,750 (15,600+14,000+1,150). We only fund in USDT and the amount is up to 30,000. Could you please help us modify the application to meet this requirement?

@NecoSherry, thank you for the excellent news!!! I have just made the adjustments to the application. Could you please review and let me know if you need anything further? Also, is there documentation as to the next steps?

**Comment by NecoSherry** [comment]
@jgophd Thank you for the update! There is currently no issue with the application. 

We need to contact you via email for the first milestone payment. Could you please send an email to [grant@vechain.org](mailto:grant@vechain.org) with your project name, PR link, Ethereum address (same as the address in your application)? As soon as the fund is disbursed, we will email you the TxID to let you know.

**Review by NecoSherry — APPROVED** [review]

**Review by zzGHzz — APPROVED** [review]

**Comment by jgophd** [comment]
> @jgophd Thank you for the update! There is currently no issue with the application.
> 
> We need to contact you via email for the first milestone payment. Could you please send an email to [grant@vechain.org](mailto:grant@vechain.org) with your project name, PR link, Ethereum address (same as the address in your application)? As soon as the fund is disbursed, we will email you the TxID to let you know.

@NecoSherry, thanks a lot, and I just sent over this information.

**Pull request merged**
