### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by BloomDAO**
# Grant Application Checklist

- [ ] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] An Ethereum address for the payment of the milestones is provided inside the application.  
- [ ] The total funding amount of the project is up to USD $30k for every grant applications.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] If you own an Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to grant@vechain.org to claim the additional grant.

### CODE REVIEW

**Comment by NecoSherry** [comment]
@BloomDAO  Thanks for the application. 

Could you update the application? See https://github.com/vechain/grant-program/blob/master/applications/application-template.md. Delete the description of each section from the template. Fill out the application with the information required, instead of leaving the link of the deck and the video. 

By the way, the grant only paid in USDT(ERC-20). Could you please provide an USDT(ERC-20) address for payment?

**Comment by NecoSherry** [comment]
update the milestone deliverables? See https://github.com/vechain/grant-program/blob/master/applications/application-template.md. Deliverables 0a-0c are mandatory for all milestones. If you do not intend to deliver one of these, please state a reason in its specification (e.g. Milestone X is research oriented and as such there is no code to test).

**Comment by VioletaMisheva** [comment]
Milestone deliverables updated @NecoSherry

**Comment by NecoSherry** [comment]
@BloomDAO  Thank you for submitting an application to our grant program. It is unfortunate that your application has been rejected by the grant committee.  The quality of the application was considered poor from every aspect the committee evaluated an application. The application doesn't include sufficient information about how you will integrate VeChain tools and features (e.g., Sync2/Connex, fee delegation protocols, MTT, etc), and how the project will be run in future in the ecosystem of VeChain. 

I’m therefore closing the PR. You're welcome to improve the application and to apply again. In any case, we thank you for your interest in the grant program.

**Pull request closed without merging**
