### PR TITLE
Add applications/Socialnft.md

### PR DESCRIPTION
**Pull request by editorai**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [ ] If you own an Economic Node or Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to bounty@vechain.com to claim the additional grant.

### CODE REVIEW

**Comment by NecoSherry** [comment]
@editorai  Thanks for your application. Sounds like an interesting project. I have a few questions:

- The mockup requires a password to access. Could you send your password with the application's initial PR link to grant@vechain.org? 
- More information about your team is needed. Could you update the pr with the resumes of team members?
- Edit and check the boxes in the checklist when creating a pull request.

**Comment by NecoSherry** [comment]
@editorai We have already received your email. Thanks for your reply. We still have some questions:

### Team
You provided a Linkedin profile in your email. Who does this Linkedin profile belong to in your team? We want to know more about all your team members, such like CVs and roles in your project. Also, we could not open the links below written in your application.

> ### Team Code Repos
> - https://github.com/editorai/socialnft-web
> - https://github.com/editorai/socialnft-api
> - https://github.com/editorai/marshmallow-v1

### Previous project
In your application, you mentioned that you had developed a Crypto Art Market. Would you please provide the website link and GitHub repo in your application?
  > Our previous developed NFT market is the earliest Chinese version of Cryptoart Market based on ERC721 launched in 2020. The platform so far has almost 1000 artist with 500+ artwork uploaded. More than 300 artworks were sold at the average prive above 1 ETH. We are fully experience with creating NFT market.

**Comment by editorai** [comment]
Can we share those information with you privately?

**Comment by NecoSherry** [comment]
> Can we share those information with you privately?

@editorai  Sure. You could send a mail to grant@vechain.org. Thanks.

**Comment by NecoSherry** [comment]
Thanks for your reply via email. We have reviewed your application.  If the followings are provided, it will be more helpful for preliminary reviewing the application:

1.  It’s ok for your team to be anonymous. Could you share us some additional information, such as previous projects, developing experience of your team members?

2. For the milestones, it seems that milestone 2 has a much more high workload than milestone 1, but the two milestones will need the same duration and FTE. Could you update your milestones to clarify your plan of the project? We recommend that you could make the milestones more detailed and fit with the budget.

**Comment by editorai** [comment]
Thanks for your comment.

1. I will share with you our pitch deck of cases via email.
2. I can hardly agree with that. Milestone 1 has a lot of works to do including detailed product and UI design, connecting and testing facebook API, setting up filecoin and ipfs storage, all frontend and non-blockchain backend realization. That's why we estimate the milestone 1 and 2 shall have a similar workload.

**Review by editorai — COMMENTED** [review]
update milestone to make it more clear. thanks for reminding.

**Review by pakorn186c — APPROVED** [review]

**Comment by editorai** [comment]
we have sent the evm prototype video to your email. You can provide your instagram account to test by yourselves as well.

**Comment by NecoSherry** [comment]
Hi, @editorai. Thank you for submitting an application to our grant program. It is unfortunate that your application has been rejected by the grant committee. 

Despite the fact that committee members appreciate the idea, they believe that your application be further improved before it is qualified for a grant. In particular, you need to work more on the "milestones" and "budget" sections to make it more reasonable and detailed. It would be also helpful if you could provide a reasonable plan for running the project in future. 

The grant committee encourages you to resubmit your application after you address the above issues.

**Pull request closed without merging**
