### PR TITLE
Stratisnik patch 1 - miden

### PR DESCRIPTION
**Pull request by stratisnik**
# Grant Application Checklist

- [X] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [X] An Ethereum address for the payment of the milestones is provided inside the application.  
- [X] The total funding amount of the project is up to USD $30k for every grant applications.
- [X] The initial PR contains only one commit (squash if needed before submitting your PR).
- [X] If you own an Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to grant@vechain.org to claim the additional grant.

### CODE REVIEW

**Comment by stratisnik** [comment]
@NecoSherry Please note that we are ready for review. In case that anything else is needed please let us know.

**Comment by mongelly** [comment]
Thank you for submitting your application. I have some questions:

Q1. How do you verify the user's tree planting behavior, including the planting location and tree type. Or you have a partner to help you with the validation work.

Q2. How do you obtain the funds needed for the subsequent operation of the project.

**Comment by stratisnik** [comment]
Hi Thank you for your comments. Please see the answers to your questions below;

1) Plantation will be controlled by the platform in the sense that miden's representatives will have to be present for the minting of NFTs at the time of the plantation. Periodic reviews on planted trees will also be performed by the platform. Planted trees will also be verified by independent service providers. Currently we are in discussions with PwC Cyprus in relation to the details of such engagement and the plan is to engage in discussions with DNV as well in the near future.

2) Through uQualify, our partner and shareholder miden gets access to several financing options from funds and investors. The development of our MVP through the grant will enhance our business case when we are ready to enter into an investment round. Currently we are engaging in discussions with funds and VCs for equity based financing after the development of our MVP. Miden will be financial sustainable through the following revenue streams that will arise after the development of the MVP;

- Initial sale of NFTs to users
- Donations and grants
- Revenue generating gamification activities (watering of trees, treatment, etc)

Thank you!

**Comment by stratisnik** [comment]
@mongelly and @NecoSherry do we have any updates on that?

**Comment by mongelly** [comment]
@stratisnik  Hi , sorry for the late reply.  I have not any questions. We will submit your project to the committee for scoring.

**Review by NecoSherry — APPROVED** [review]

**Review by mongelly — APPROVED** [review]

**Comment by NecoSherry** [comment]
@stratisnik Congratulations! Your application has been accepted by the committee!

We would like to inform you that we have recently updated our payment currency to USDC (ERC 20). Therefore, we kindly ask you to confirm that your payment address is capable of receiving USDC payments. To ensure a smooth process, we will make a small test payment after your confirmation before the first payout.

In order to proceed with further payments, we need to contact you by email. Please send an email to [grant@vechain.org](mailto:grant@vechain.org) with your project name, PR link and payment address (same as in the PR).

**Pull request merged**
