### PR TITLE
Create MotoDB

### PR DESCRIPTION
**Pull request by vedantk16**
# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] If you own an Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to grant@vechain.org to claim the additional grant.

### CODE REVIEW

**Comment by vedantk16** [comment]
I have committed to the master branch. Is this the right way to apply for the grant?

**Comment by vedantk16** [comment]
Any updates on the grant? Do you require anything else from my side?

**Comment by vedantk16** [comment]
Any updates on the grant?

**Comment by NecoSherry** [comment]
Hi, XXX. Thank you for submitting an application to our grant program. It is unfortunate that your application has been rejected by the grant committee. The following are the main reasons your application was rejected:
1. The quality of the application was considered poor from every aspect the committee evaluated an application.
2. The overall business logic of the project is not sufficiently clarified, which makes it difficult to evaluate the value and impact of the project to our ecosystem.
3. The application contains insufficient details of technical development and milestones.

**Pull request closed without merging**
