### PR TITLE
Grant Extractor (M1, M2 and M3 deliverables)

### PR DESCRIPTION
**Pull request by andriyk-hacken**
# Grant Application Checklist

- [ ] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] An Ethereum address for the payment of the milestones is provided inside the application.  
- [ ] The total funding amount of the project is up to USD $30k for every grant applications.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Comment by NecoSherry** [comment]
@andriyk-hacken Thank you for delivering M2 and M3. I noticed that M1 has not been delivered yet. Could you please include the delivery of M1 as well? The review needs to follow the milestones accordingly. Thank you for your cooperation.

**Comment by andriyk-hacken** [comment]
Added Milestone-1 deliverables

**Comment by andriyk-hacken** [comment]
Hey, guys, any progress on Milestone deliveries review ?

**Review by libotony — APPROVED** [review]

**Comment by NecoSherry** [comment]
Thank you for the delivery. We will promptly proceed with the payment process for milestones 2 and milestone 3. Before we make the payment, could you please confirm if the payment address is still the same as in your application?

**Review by NecoSherry — APPROVED** [review]

**Comment by andriyk-hacken** [comment]
@NecoSherry 
Address is different. Shall I post a new address here ?

**Comment by NecoSherry** [comment]
@andriyk-hacken You need to change your address by creating a new pull request to update it in your application.

**Pull request merged**
